baseURL: "https://visola.org/"
languageCode: "en-us"
title: "Vinnie's Place"

sectionPagesMenu: "main"

menu:
  links:
    - identifier: "github"
      name: "GitHub"
      url: "https://github.com/visola/"

    - identifier: "rss"
      name: "RSS"
      url: "/index.xml"

    - identifier: "stackoverflow"
      name: "StackOverflow"
      url: "http://stackoverflow.com/users/2731402/visola"

    - identifier: "twitter"
      name: "Twitter"
      url: "http://twitter.com/IsolaVinicius"
